// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a commit in the history
 */
export type CommitInfo = { hash: string, message: string, author: string, timestamp: string, };
