// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Container domain model
 *
 * A Container represents an organizational entity within a Universe that can contain
 * either child containers or stories. Examples include novels, series, collections.
 * Containers support nesting: a "series" can contain "novels", and "novels" can contain
 * "chapters" (which are stories, not containers).
 *
 * Only leaf containers (those containing stories, not child containers) have Git repositories.
 */
export type Container = { id: string, universeId: string, parentContainerId: string | null, containerType: string, title: string, description: string | null, order: number, gitRepoPath: string | null, currentBranch: string | null, stagedChanges: boolean, createdAt: string, updatedAt: string, };
