// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Container domain model
 *
 * A Container represents an organizational entity within a Universe that can contain
 * either child containers or stories. Examples include novels, series, collections.
 * Containers support nesting: a "series" can contain "novels", and "novels" can contain
 * "chapters" (which are stories, not containers).
 *
 * With Database-Only Versioning (DBV), containers no longer have Git repositories.
 * Versioning is handled at the story level through versions and snapshots.
 */
export type Container = { id: string, universeId: string, parentContainerId: string | null, containerType: string, title: string, description: string | null, order: number, createdAt: string, updatedAt: string, };
