// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a new Container
 */
export type CreateContainerInput = { universeId: string, parentContainerId: string | null, containerType: string, title: string, description: string | null, order: number | null, };
