// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoryType } from "./StoryType";
import type { VariationType } from "./VariationType";

/**
 * Input for creating a new Story
 */
export type CreateStoryInput = { universeId: string, title: string, description: string | null, storyType: StoryType | null, content: string | null, notes: string | null, outline: string | null, targetWordCount: number | null, tags: Array<string> | null, color: string | null, seriesName: string | null, parentStoryId: string | null, variationType: VariationType | null, parentVariationId: string | null, };
