// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementRelationship } from "./ElementRelationship";
import type { ElementType } from "./ElementType";

/**
 * Input for creating a new Element
 */
export type CreateElementInput = { universeId: string, name: string, description: string | null, elementType: ElementType | null, customTypeName: string | null, details: string | null, attributes: { [key in string]?: string } | null, imageUrl: string | null, tags: Array<string> | null, relationships: Array<ElementRelationship> | null, color: string | null, icon: string | null, };
