// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Genre } from "./Genre";
import type { Tone } from "./Tone";

/**
 * Input for creating a new Universe
 */
export type CreateUniverseInput = { name: string, description: string | null, genre: Genre | null, tone: Tone | null, worldbuildingNotes: string | null, themes: Array<string> | null, color: string | null, icon: string | null, tags: Array<string> | null, };
