// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a new StoryVersion
 */
export type CreateStoryVersionInput = { storyId: string, name: string, content: string | null, };
