// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

/**
 * Result of a diff operation between two branches
 */
export type DiffResult = { changes: Array<FileChange>, };
