// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relationship between elements with flexible labeling
 */
export type ElementRelationship = { 
/**
 * ID of the target element this relationship points to
 */
targetElementId: string, 
/**
 * Label describing the relationship from source to target
 * Examples: "best friend", "owns", "lives in", "captain of"
 */
label: string, 
/**
 * Optional inverse label for bidirectional queries
 * Examples: "best friend of", "owned by", "home of", "captained by"
 */
inverseLabel: string | null, 
/**
 * Optional additional context about this relationship
 */
description: string | null, };
