// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementRelationship } from "./ElementRelationship";
import type { ElementType } from "./ElementType";

/**
 * Element domain model
 *
 * An Element is any entity within a Universe that can be referenced in stories.
 * Elements can be characters, locations, vehicles, items, organizations, or any
 * custom type the author needs.
 */
export type Element = { id: string, universeId: string, name: string, description: string, createdAt: string, updatedAt: string, elementType: ElementType, customTypeName: string | null, details: string | null, attributes: { [key in string]?: string } | null, imageUrl: string | null, tags: Array<string> | null, relationships: Array<ElementRelationship> | null, relatedStoryIds: Array<string> | null, color: string | null, icon: string | null, favorite: boolean | null, order: number | null, };
