// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeStatus } from "./ChangeStatus";

/**
 * Represents a file change in a diff
 */
export type FileChange = { path: string, status: ChangeStatus, diff: string | null, };
