/**
 * Types barrel export
 *
 * Auto-generated TypeScript types from Rust backend models.
 * These types are generated by ts-rs from Rust structs.
 *
 * DO NOT EDIT MANUALLY - regenerate with: cd src-tauri && cargo test --lib
 */

// Domain models
export type { Universe } from './Universe';
export type { Story } from './Story';
export type { Element } from './Element';
export type { Container } from './Container';

// Universe types
export type { UniverseStatus } from './UniverseStatus';
export type { Genre } from './Genre';
export type { Tone } from './Tone';
export type { CreateUniverseInput } from './CreateUniverseInput';
export type { UpdateUniverseInput } from './UpdateUniverseInput';

// Story types
export type { StoryStatus } from './StoryStatus';
export type { StoryType } from './StoryType';
export type { VariationType } from './VariationType';
export type { CreateStoryInput } from './CreateStoryInput';
export type { UpdateStoryInput } from './UpdateStoryInput';

// Element types
export type { ElementType } from './ElementType';
export type { ElementRelationship } from './ElementRelationship';
export type { CreateElementInput } from './CreateElementInput';
export type { UpdateElementInput } from './UpdateElementInput';

// Container types
export type { CreateContainerInput } from './CreateContainerInput';
export type { UpdateContainerInput } from './UpdateContainerInput';
export type { ContainerChildren } from './ContainerChildren';

// Git types
export type { CommitInfo } from './CommitInfo';
export type { DiffResult } from './DiffResult';
export type { FileChange } from './FileChange';
export type { ChangeStatus } from './ChangeStatus';
export type { MergeResult } from './MergeResult';
export type { VariationInfo } from './VariationInfo';

// Utility types for partial updates
// These convert `field: T | null` types to `field?: T | null` for easier usage
import type { UpdateStoryInput as _UpdateStoryInput } from './UpdateStoryInput';
import type { UpdateElementInput as _UpdateElementInput } from './UpdateElementInput';
import type { UpdateUniverseInput as _UpdateUniverseInput } from './UpdateUniverseInput';

/**
 * Makes all nullable fields optional.
 * Converts { field: T | null } to { field?: T | null }
 */
export type PartialNullable<T> = {
  [K in keyof T]?: T[K];
};

/**
 * Partial update type for Story - only include fields you want to change
 */
export type StoryUpdate = PartialNullable<_UpdateStoryInput>;

/**
 * Partial update type for Element - only include fields you want to change
 */
export type ElementUpdate = PartialNullable<_UpdateElementInput>;

/**
 * Partial update type for Universe - only include fields you want to change
 */
export type UniverseUpdate = PartialNullable<_UpdateUniverseInput>;
