// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a merge operation
 */
export type MergeResult = { success: boolean, conflicts: Array<string>, message: string, };
