// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for renaming an existing StoryVersion
 */
export type RenameStoryVersionInput = { versionId: string, newName: string, };
