// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorySnapshot } from "./StorySnapshot";
import type { StoryStatus } from "./StoryStatus";
import type { StoryType } from "./StoryType";
import type { StoryVersion } from "./StoryVersion";
import type { VariationType } from "./VariationType";

/**
 * Rich Story representation for single-story endpoints (get_story).
 *
 * Includes the active version and snapshot data inline, guaranteeing
 * they are present (non-optional) for a properly initialized story.
 */
export type StoryDetail = { id: string, universeId: string, title: string, description: string, createdAt: string, updatedAt: string, storyType: StoryType, status: StoryStatus, wordCount: number, targetWordCount: number | null, notes: string | null, outline: string | null, order: number | null, tags: Array<string> | null, color: string | null, favorite: boolean | null, relatedElementIds: Array<string> | null, containerId: string | null, seriesName: string | null, lastEditedAt: string, version: number, variationGroupId: string, variationType: VariationType, parentVariationId: string | null, activeVersionId: string, activeSnapshotId: string, activeVersion: StoryVersion, activeSnapshot: StorySnapshot, };
