// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoryStatus } from "./StoryStatus";
import type { StoryType } from "./StoryType";
import type { VariationType } from "./VariationType";

/**
 * Story domain model
 *
 * A Story is a written work within a Universe. It can be a novel, script, screenplay,
 * or any other type of creative writing. Stories support variations and Git-based versioning.
 */
export type Story = { id: string, universeId: string, title: string, description: string, createdAt: string, updatedAt: string, storyType: StoryType, status: StoryStatus, wordCount: number, targetWordCount: number | null, content: string, notes: string | null, outline: string | null, order: number | null, tags: Array<string> | null, color: string | null, favorite: boolean | null, relatedElementIds: Array<string> | null, containerId: string | null, seriesName: string | null, lastEditedAt: string, version: number, variationGroupId: string, variationType: VariationType, parentVariationId: string | null, gitRepoPath: string, currentBranch: string, stagedChanges: boolean, };
