// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoryType = "novel" | "short-story" | "script" | "screenplay" | "episode" | "chapter" | "poem" | "article" | "other";
