// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoryStatus } from "./StoryStatus";
import type { StoryType } from "./StoryType";
import type { VariationType } from "./VariationType";

/**
 * Lightweight Story representation for list endpoints.
 *
 * Excludes hydrated version/snapshot data to keep list responses lean.
 * Used by `list_stories_by_universe`, `list_stories_by_container`, etc.
 */
export type StorySummary = { id: string, universeId: string, title: string, description: string, createdAt: string, updatedAt: string, storyType: StoryType, status: StoryStatus, wordCount: number, targetWordCount: number | null, order: number | null, tags: Array<string> | null, color: string | null, favorite: boolean | null, containerId: string | null, seriesName: string | null, lastEditedAt: string, version: number, variationGroupId: string, variationType: VariationType, parentVariationId: string | null, };
