// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * StorySnapshot domain model
 *
 * A StorySnapshot represents a point-in-time save of content within a version.
 * Snapshots are created automatically (via auto-snapshot system) and can be
 * restored to recover previous states of a story's content.
 *
 * This is part of the Database-Only Versioning (DBV) system:
 * - Story → Version → Snapshot hierarchy
 * - Snapshots are automatic saves within a version
 * - Users can restore to any previous snapshot
 */
export type StorySnapshot = { 
/**
 * Unique identifier for the snapshot
 */
id: string, 
/**
 * ID of the version this snapshot belongs to
 */
versionId: string, 
/**
 * The actual content text at this point in time
 */
content: string, 
/**
 * ISO 8601 timestamp when this snapshot was created
 */
createdAt: string, };
