// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * StoryVersion domain model
 *
 * A StoryVersion represents a named variation of a story (e.g., "Original", "Alternate Ending").
 * Each version contains one or more snapshots, which are point-in-time saves of the content.
 * This is part of the Database-Only Versioning (DBV) system that replaces Git-based versioning.
 */
export type StoryVersion = { id: string, storyId: string, name: string, createdAt: string, updatedAt: string, };
