// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Genre } from "./Genre";
import type { Tone } from "./Tone";
import type { UniverseStatus } from "./UniverseStatus";

/**
 * Universe domain model
 *
 * A Universe is a project container for creative work, holding all the context,
 * elements, and stories that belong to a particular creative world.
 */
export type Universe = { id: string, name: string, description: string, createdAt: string, updatedAt: string, genre: Genre | null, tone: Tone | null, worldbuildingNotes: string | null, themes: Array<string> | null, status: UniverseStatus, color: string | null, icon: string | null, tags: Array<string> | null, };
