// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for updating an existing Container
 */
export type UpdateContainerInput = { title: string | null, description: string | null, containerType: string | null, order: number | null, };
