// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Genre } from "./Genre";
import type { Tone } from "./Tone";
import type { UniverseStatus } from "./UniverseStatus";

/**
 * Input for updating an existing Universe
 */
export type UpdateUniverseInput = { name: string | null, description: string | null, genre: Genre | null, tone: Tone | null, worldbuildingNotes: string | null, themes: Array<string> | null, status: UniverseStatus | null, color: string | null, icon: string | null, tags: Array<string> | null, };
