// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a story variation (Git branch with display name)
 *
 * This struct represents a variation/branch in a story's Git repository,
 * combining the Git branch name (slug) with its user-friendly display name.
 */
export type VariationInfo = { 
/**
 * Git branch name (slug), e.g., "what-if-sarah-lived"
 */
slug: string, 
/**
 * User-facing display name, e.g., "What if Sarah lived?"
 */
display_name: string, 
/**
 * Is this the currently active branch?
 */
is_current: boolean, 
/**
 * Is this the original/main branch?
 */
is_original: boolean, };
